//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightRouteClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Airplane", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Airplane : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Flight[] FlightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int airplaneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int seatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Flight[] Flights {
            get {
                return this.FlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightsField, value) != true)) {
                    this.FlightsField = value;
                    this.RaisePropertyChanged("Flights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int airplaneID {
            get {
                return this.airplaneIDField;
            }
            set {
                if ((this.airplaneIDField.Equals(value) != true)) {
                    this.airplaneIDField = value;
                    this.RaisePropertyChanged("airplaneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int seats {
            get {
                return this.seatsField;
            }
            set {
                if ((this.seatsField.Equals(value) != true)) {
                    this.seatsField = value;
                    this.RaisePropertyChanged("seats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Airplane AirplaneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Airport AirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Airport Airport1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.BookingFlight[] BookingFlightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> airplaneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flightIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int takenSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeOfArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeOfDepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int toField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> traveltimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Airplane Airplane {
            get {
                return this.AirplaneField;
            }
            set {
                if ((object.ReferenceEquals(this.AirplaneField, value) != true)) {
                    this.AirplaneField = value;
                    this.RaisePropertyChanged("Airplane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Airport Airport {
            get {
                return this.AirportField;
            }
            set {
                if ((object.ReferenceEquals(this.AirportField, value) != true)) {
                    this.AirportField = value;
                    this.RaisePropertyChanged("Airport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Airport Airport1 {
            get {
                return this.Airport1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Airport1Field, value) != true)) {
                    this.Airport1Field = value;
                    this.RaisePropertyChanged("Airport1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.BookingFlight[] BookingFlights {
            get {
                return this.BookingFlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingFlightsField, value) != true)) {
                    this.BookingFlightsField = value;
                    this.RaisePropertyChanged("BookingFlights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> airplaneID {
            get {
                return this.airplaneIDField;
            }
            set {
                if ((this.airplaneIDField.Equals(value) != true)) {
                    this.airplaneIDField = value;
                    this.RaisePropertyChanged("airplaneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flightID {
            get {
                return this.flightIDField;
            }
            set {
                if ((this.flightIDField.Equals(value) != true)) {
                    this.flightIDField = value;
                    this.RaisePropertyChanged("flightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int from {
            get {
                return this.fromField;
            }
            set {
                if ((this.fromField.Equals(value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int takenSeats {
            get {
                return this.takenSeatsField;
            }
            set {
                if ((this.takenSeatsField.Equals(value) != true)) {
                    this.takenSeatsField = value;
                    this.RaisePropertyChanged("takenSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string timeOfArrival {
            get {
                return this.timeOfArrivalField;
            }
            set {
                if ((object.ReferenceEquals(this.timeOfArrivalField, value) != true)) {
                    this.timeOfArrivalField = value;
                    this.RaisePropertyChanged("timeOfArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string timeOfDeparture {
            get {
                return this.timeOfDepartureField;
            }
            set {
                if ((object.ReferenceEquals(this.timeOfDepartureField, value) != true)) {
                    this.timeOfDepartureField = value;
                    this.RaisePropertyChanged("timeOfDeparture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int to {
            get {
                return this.toField;
            }
            set {
                if ((this.toField.Equals(value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> traveltime {
            get {
                return this.traveltimeField;
            }
            set {
                if ((this.traveltimeField.Equals(value) != true)) {
                    this.traveltimeField = value;
                    this.RaisePropertyChanged("traveltime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Airport", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Airport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Flight[] FlightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Flight[] Flights1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int airportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Flight[] Flights {
            get {
                return this.FlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightsField, value) != true)) {
                    this.FlightsField = value;
                    this.RaisePropertyChanged("Flights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Flight[] Flights1 {
            get {
                return this.Flights1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Flights1Field, value) != true)) {
                    this.Flights1Field = value;
                    this.RaisePropertyChanged("Flights1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int airportID {
            get {
                return this.airportIDField;
            }
            set {
                if ((this.airportIDField.Equals(value) != true)) {
                    this.airportIDField = value;
                    this.RaisePropertyChanged("airportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingFlight", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class BookingFlight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Booking BookingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Flight FlightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bookingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flightIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Booking Booking {
            get {
                return this.BookingField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingField, value) != true)) {
                    this.BookingField = value;
                    this.RaisePropertyChanged("Booking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Flight Flight {
            get {
                return this.FlightField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightField, value) != true)) {
                    this.FlightField = value;
                    this.RaisePropertyChanged("Flight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookingID {
            get {
                return this.bookingIDField;
            }
            set {
                if ((this.bookingIDField.Equals(value) != true)) {
                    this.bookingIDField = value;
                    this.RaisePropertyChanged("bookingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flightID {
            get {
                return this.flightIDField;
            }
            set {
                if ((this.flightIDField.Equals(value) != true)) {
                    this.flightIDField = value;
                    this.RaisePropertyChanged("flightID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.BookingFlight[] BookingFlightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.BookingPassenger[] BookingPassengersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bookingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> totalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string totalTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.BookingFlight[] BookingFlights {
            get {
                return this.BookingFlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingFlightsField, value) != true)) {
                    this.BookingFlightsField = value;
                    this.RaisePropertyChanged("BookingFlights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.BookingPassenger[] BookingPassengers {
            get {
                return this.BookingPassengersField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingPassengersField, value) != true)) {
                    this.BookingPassengersField = value;
                    this.RaisePropertyChanged("BookingPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookingID {
            get {
                return this.bookingIDField;
            }
            set {
                if ((this.bookingIDField.Equals(value) != true)) {
                    this.bookingIDField = value;
                    this.RaisePropertyChanged("bookingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                if ((this.totalPriceField.Equals(value) != true)) {
                    this.totalPriceField = value;
                    this.RaisePropertyChanged("totalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalTime {
            get {
                return this.totalTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.totalTimeField, value) != true)) {
                    this.totalTimeField = value;
                    this.RaisePropertyChanged("totalTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingPassenger", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class BookingPassenger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Booking BookingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bookingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int personIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Booking Booking {
            get {
                return this.BookingField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingField, value) != true)) {
                    this.BookingField = value;
                    this.RaisePropertyChanged("Booking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookingID {
            get {
                return this.bookingIDField;
            }
            set {
                if ((this.bookingIDField.Equals(value) != true)) {
                    this.bookingIDField = value;
                    this.RaisePropertyChanged("bookingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int personID {
            get {
                return this.personIDField;
            }
            set {
                if ((this.personIDField.Equals(value) != true)) {
                    this.personIDField = value;
                    this.RaisePropertyChanged("personID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightRouteClient.ServiceReference1.BookingPassenger[] BookingPassengersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string birthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int personIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightRouteClient.ServiceReference1.BookingPassenger[] BookingPassengers {
            get {
                return this.BookingPassengersField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingPassengersField, value) != true)) {
                    this.BookingPassengersField = value;
                    this.RaisePropertyChanged("BookingPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthdate {
            get {
                return this.birthdateField;
            }
            set {
                if ((object.ReferenceEquals(this.birthdateField, value) != true)) {
                    this.birthdateField = value;
                    this.RaisePropertyChanged("birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fnameField, value) != true)) {
                    this.fnameField = value;
                    this.RaisePropertyChanged("fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lnameField, value) != true)) {
                    this.lnameField = value;
                    this.RaisePropertyChanged("lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int personID {
            get {
                return this.personIDField;
            }
            set {
                if ((this.personIDField.Equals(value) != true)) {
                    this.personIDField = value;
                    this.RaisePropertyChanged("personID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNoField, value) != true)) {
                    this.phoneNoField = value;
                    this.RaisePropertyChanged("phoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFlightService")]
    public interface IFlightService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAllAirplanes", ReplyAction="http://tempuri.org/IFlightService/GetAllAirplanesResponse")]
        FlightRouteClient.ServiceReference1.Airplane[] GetAllAirplanes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAllAirplanes", ReplyAction="http://tempuri.org/IFlightService/GetAllAirplanesResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Airplane[]> GetAllAirplanesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewAirplane", ReplyAction="http://tempuri.org/IFlightService/CreateNewAirplaneResponse")]
        bool CreateNewAirplane(int seats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewAirplane", ReplyAction="http://tempuri.org/IFlightService/CreateNewAirplaneResponse")]
        System.Threading.Tasks.Task<bool> CreateNewAirplaneAsync(int seats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAirplaneByID", ReplyAction="http://tempuri.org/IFlightService/GetAirplaneByIDResponse")]
        FlightRouteClient.ServiceReference1.Airplane GetAirplaneByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAirplaneByID", ReplyAction="http://tempuri.org/IFlightService/GetAirplaneByIDResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Airplane> GetAirplaneByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdateAirplane", ReplyAction="http://tempuri.org/IFlightService/UpdateAirplaneResponse")]
        bool UpdateAirplane(int id, int seats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdateAirplane", ReplyAction="http://tempuri.org/IFlightService/UpdateAirplaneResponse")]
        System.Threading.Tasks.Task<bool> UpdateAirplaneAsync(int id, int seats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeleteAirplane", ReplyAction="http://tempuri.org/IFlightService/DeleteAirplaneResponse")]
        bool DeleteAirplane(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeleteAirplane", ReplyAction="http://tempuri.org/IFlightService/DeleteAirplaneResponse")]
        System.Threading.Tasks.Task<bool> DeleteAirplaneAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAllFlights", ReplyAction="http://tempuri.org/IFlightService/GetAllFlightsResponse")]
        FlightRouteClient.ServiceReference1.Flight[] GetAllFlights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAllFlights", ReplyAction="http://tempuri.org/IFlightService/GetAllFlightsResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight[]> GetAllFlightsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightByID", ReplyAction="http://tempuri.org/IFlightService/GetFlightByIDResponse")]
        FlightRouteClient.ServiceReference1.Flight GetFlightByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightByID", ReplyAction="http://tempuri.org/IFlightService/GetFlightByIDResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight> GetFlightByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightsByDate", ReplyAction="http://tempuri.org/IFlightService/GetFlightsByDateResponse")]
        FlightRouteClient.ServiceReference1.Flight[] GetFlightsByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightsByDate", ReplyAction="http://tempuri.org/IFlightService/GetFlightsByDateResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight[]> GetFlightsByDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightsFrom", ReplyAction="http://tempuri.org/IFlightService/GetFlightsFromResponse")]
        FlightRouteClient.ServiceReference1.Flight[] GetFlightsFrom(FlightRouteClient.ServiceReference1.Airport start, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightsFrom", ReplyAction="http://tempuri.org/IFlightService/GetFlightsFromResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight[]> GetFlightsFromAsync(FlightRouteClient.ServiceReference1.Airport start, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewFlight", ReplyAction="http://tempuri.org/IFlightService/CreateNewFlightResponse")]
        void CreateNewFlight(string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewFlight", ReplyAction="http://tempuri.org/IFlightService/CreateNewFlightResponse")]
        System.Threading.Tasks.Task CreateNewFlightAsync(string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdateFlight", ReplyAction="http://tempuri.org/IFlightService/UpdateFlightResponse")]
        void UpdateFlight(int id, string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdateFlight", ReplyAction="http://tempuri.org/IFlightService/UpdateFlightResponse")]
        System.Threading.Tasks.Task UpdateFlightAsync(int id, string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeleteFlight", ReplyAction="http://tempuri.org/IFlightService/DeleteFlightResponse")]
        void DeleteFlight(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeleteFlight", ReplyAction="http://tempuri.org/IFlightService/DeleteFlightResponse")]
        System.Threading.Tasks.Task DeleteFlightAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAirportByID", ReplyAction="http://tempuri.org/IFlightService/GetAirportByIDResponse")]
        FlightRouteClient.ServiceReference1.Airport GetAirportByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAirportByID", ReplyAction="http://tempuri.org/IFlightService/GetAirportByIDResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Airport> GetAirportByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewAirport", ReplyAction="http://tempuri.org/IFlightService/CreateNewAirportResponse")]
        void CreateNewAirport(string name, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewAirport", ReplyAction="http://tempuri.org/IFlightService/CreateNewAirportResponse")]
        System.Threading.Tasks.Task CreateNewAirportAsync(string name, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdateAirport", ReplyAction="http://tempuri.org/IFlightService/UpdateAirportResponse")]
        void UpdateAirport(int id, string name, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdateAirport", ReplyAction="http://tempuri.org/IFlightService/UpdateAirportResponse")]
        System.Threading.Tasks.Task UpdateAirportAsync(int id, string name, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeleteAirport", ReplyAction="http://tempuri.org/IFlightService/DeleteAirportResponse")]
        void DeleteAirport(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeleteAirport", ReplyAction="http://tempuri.org/IFlightService/DeleteAirportResponse")]
        System.Threading.Tasks.Task DeleteAirportAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAllPersons", ReplyAction="http://tempuri.org/IFlightService/GetAllPersonsResponse")]
        FlightRouteClient.ServiceReference1.Person[] GetAllPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetAllPersons", ReplyAction="http://tempuri.org/IFlightService/GetAllPersonsResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Person[]> GetAllPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetPersonByID", ReplyAction="http://tempuri.org/IFlightService/GetPersonByIDResponse")]
        FlightRouteClient.ServiceReference1.Person GetPersonByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetPersonByID", ReplyAction="http://tempuri.org/IFlightService/GetPersonByIDResponse")]
        System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Person> GetPersonByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewPerson", ReplyAction="http://tempuri.org/IFlightService/CreateNewPersonResponse")]
        void CreateNewPerson(string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CreateNewPerson", ReplyAction="http://tempuri.org/IFlightService/CreateNewPersonResponse")]
        System.Threading.Tasks.Task CreateNewPersonAsync(string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdatePerson", ReplyAction="http://tempuri.org/IFlightService/UpdatePersonResponse")]
        bool UpdatePerson(int id, string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/UpdatePerson", ReplyAction="http://tempuri.org/IFlightService/UpdatePersonResponse")]
        System.Threading.Tasks.Task<bool> UpdatePersonAsync(int id, string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeletePerson", ReplyAction="http://tempuri.org/IFlightService/DeletePersonResponse")]
        bool DeletePerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/DeletePerson", ReplyAction="http://tempuri.org/IFlightService/DeletePersonResponse")]
        System.Threading.Tasks.Task<bool> DeletePersonAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlightServiceChannel : FlightRouteClient.ServiceReference1.IFlightService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightServiceClient : System.ServiceModel.ClientBase<FlightRouteClient.ServiceReference1.IFlightService>, FlightRouteClient.ServiceReference1.IFlightService {
        
        public FlightServiceClient() {
        }
        
        public FlightServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FlightRouteClient.ServiceReference1.Airplane[] GetAllAirplanes() {
            return base.Channel.GetAllAirplanes();
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Airplane[]> GetAllAirplanesAsync() {
            return base.Channel.GetAllAirplanesAsync();
        }
        
        public bool CreateNewAirplane(int seats) {
            return base.Channel.CreateNewAirplane(seats);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNewAirplaneAsync(int seats) {
            return base.Channel.CreateNewAirplaneAsync(seats);
        }
        
        public FlightRouteClient.ServiceReference1.Airplane GetAirplaneByID(int id) {
            return base.Channel.GetAirplaneByID(id);
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Airplane> GetAirplaneByIDAsync(int id) {
            return base.Channel.GetAirplaneByIDAsync(id);
        }
        
        public bool UpdateAirplane(int id, int seats) {
            return base.Channel.UpdateAirplane(id, seats);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAirplaneAsync(int id, int seats) {
            return base.Channel.UpdateAirplaneAsync(id, seats);
        }
        
        public bool DeleteAirplane(int id) {
            return base.Channel.DeleteAirplane(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAirplaneAsync(int id) {
            return base.Channel.DeleteAirplaneAsync(id);
        }
        
        public FlightRouteClient.ServiceReference1.Flight[] GetAllFlights() {
            return base.Channel.GetAllFlights();
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight[]> GetAllFlightsAsync() {
            return base.Channel.GetAllFlightsAsync();
        }
        
        public FlightRouteClient.ServiceReference1.Flight GetFlightByID(int id) {
            return base.Channel.GetFlightByID(id);
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight> GetFlightByIDAsync(int id) {
            return base.Channel.GetFlightByIDAsync(id);
        }
        
        public FlightRouteClient.ServiceReference1.Flight[] GetFlightsByDate(string date) {
            return base.Channel.GetFlightsByDate(date);
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight[]> GetFlightsByDateAsync(string date) {
            return base.Channel.GetFlightsByDateAsync(date);
        }
        
        public FlightRouteClient.ServiceReference1.Flight[] GetFlightsFrom(FlightRouteClient.ServiceReference1.Airport start, string date) {
            return base.Channel.GetFlightsFrom(start, date);
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Flight[]> GetFlightsFromAsync(FlightRouteClient.ServiceReference1.Airport start, string date) {
            return base.Channel.GetFlightsFromAsync(start, date);
        }
        
        public void CreateNewFlight(string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats) {
            base.Channel.CreateNewFlight(timeOfDepature, timeOfArrival, travelTime, price, from, to, airplaneID, takenSeats);
        }
        
        public System.Threading.Tasks.Task CreateNewFlightAsync(string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats) {
            return base.Channel.CreateNewFlightAsync(timeOfDepature, timeOfArrival, travelTime, price, from, to, airplaneID, takenSeats);
        }
        
        public void UpdateFlight(int id, string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats) {
            base.Channel.UpdateFlight(id, timeOfDepature, timeOfArrival, travelTime, price, from, to, airplaneID, takenSeats);
        }
        
        public System.Threading.Tasks.Task UpdateFlightAsync(int id, string timeOfDepature, string timeOfArrival, double travelTime, double price, int from, int to, int airplaneID, int takenSeats) {
            return base.Channel.UpdateFlightAsync(id, timeOfDepature, timeOfArrival, travelTime, price, from, to, airplaneID, takenSeats);
        }
        
        public void DeleteFlight(int id) {
            base.Channel.DeleteFlight(id);
        }
        
        public System.Threading.Tasks.Task DeleteFlightAsync(int id) {
            return base.Channel.DeleteFlightAsync(id);
        }
        
        public FlightRouteClient.ServiceReference1.Airport GetAirportByID(int id) {
            return base.Channel.GetAirportByID(id);
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Airport> GetAirportByIDAsync(int id) {
            return base.Channel.GetAirportByIDAsync(id);
        }
        
        public void CreateNewAirport(string name, string location) {
            base.Channel.CreateNewAirport(name, location);
        }
        
        public System.Threading.Tasks.Task CreateNewAirportAsync(string name, string location) {
            return base.Channel.CreateNewAirportAsync(name, location);
        }
        
        public void UpdateAirport(int id, string name, string location) {
            base.Channel.UpdateAirport(id, name, location);
        }
        
        public System.Threading.Tasks.Task UpdateAirportAsync(int id, string name, string location) {
            return base.Channel.UpdateAirportAsync(id, name, location);
        }
        
        public void DeleteAirport(int id) {
            base.Channel.DeleteAirport(id);
        }
        
        public System.Threading.Tasks.Task DeleteAirportAsync(int id) {
            return base.Channel.DeleteAirportAsync(id);
        }
        
        public FlightRouteClient.ServiceReference1.Person[] GetAllPersons() {
            return base.Channel.GetAllPersons();
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Person[]> GetAllPersonsAsync() {
            return base.Channel.GetAllPersonsAsync();
        }
        
        public FlightRouteClient.ServiceReference1.Person GetPersonByID(int id) {
            return base.Channel.GetPersonByID(id);
        }
        
        public System.Threading.Tasks.Task<FlightRouteClient.ServiceReference1.Person> GetPersonByIDAsync(int id) {
            return base.Channel.GetPersonByIDAsync(id);
        }
        
        public void CreateNewPerson(string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type) {
            base.Channel.CreateNewPerson(fName, lName, gender, address, phoneNo, email, birthdate, password, type);
        }
        
        public System.Threading.Tasks.Task CreateNewPersonAsync(string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type) {
            return base.Channel.CreateNewPersonAsync(fName, lName, gender, address, phoneNo, email, birthdate, password, type);
        }
        
        public bool UpdatePerson(int id, string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type) {
            return base.Channel.UpdatePerson(id, fName, lName, gender, address, phoneNo, email, birthdate, password, type);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePersonAsync(int id, string fName, string lName, string gender, string address, string phoneNo, string email, string birthdate, string password, int type) {
            return base.Channel.UpdatePersonAsync(id, fName, lName, gender, address, phoneNo, email, birthdate, password, type);
        }
        
        public bool DeletePerson(int id) {
            return base.Channel.DeletePerson(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePersonAsync(int id) {
            return base.Channel.DeletePersonAsync(id);
        }
    }
}
